#!/bin/sh

ISSUE=/etc/issue
printf '%b' "\033[36;1mDebian\033[0m GNU/Linux $(cat /etc/debian_version) \033[33;1m\\\\n\033[0m \\\\l\n\n" > "${ISSUE}"

for i in /etc/ssh/ssh_host_*_key; do
  # 2048 2d:01:fe:d3:d4:68:b3:e6:11:59:01:bc:8a:b0:d2:45  root@marc-desktop (RSA)
  set $(ssh-keygen -l -f $i)
  printf '%b' "\033[35;1m$2\033[0m $4/$1\n" >> "${ISSUE}"
done;
